version: '3'

services:
  db:
    image: thanasak/my-app:1.0
    container_name: my-db1
    ports:
      - 54321:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  pg-admin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin1
    ports:
      - 4433:443
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}

